import { WorkflowProject, WorkflowStep } from '../types';

export function calculateWorkflowStats(steps: WorkflowStep[]) {
  const total = steps.length;
  if (total === 0) {
    return {
      total: 0,
      completed: 0,
      inMotion: 0,
      turbulent: 0,
      parked: 0,
      progressPercentage: 0,
      averageChaos: 0,
      turbulenceGrade: 'Calm',
      totalEstimatedHours: 0,
    };
  }

  const completed = steps.filter((s) => s.status === 'polished').length;
  const inMotion = steps.filter((s) => s.status === 'in_motion').length;
  const turbulent = steps.filter((s) => s.status === 'turbulent').length;
  const parked = steps.filter((s) => s.status === 'parked').length;

  const progressPercentage = Math.round((completed / total) * 100);

  const totalChaos = steps.reduce((acc, curr) => acc + (curr.chaosLevel || 1), 0);
  const averageChaos = Number((totalChaos / total).toFixed(1));

  let turbulenceGrade = 'Calm';
  if (averageChaos >= 4.0) turbulenceGrade = 'Severe Storm 🌪️';
  else if (averageChaos >= 3.0) turbulenceGrade = 'Moderate Turbulence ⚡';
  else if (averageChaos >= 2.0) turbulenceGrade = 'Gentle Current 🌊';
  else turbulenceGrade = 'Crystal Clear 💎';

  const totalMinutes = steps.reduce((acc, curr) => acc + (curr.estimatedMinutes || 0), 0);
  const totalEstimatedHours = Number((totalMinutes / 60).toFixed(1));

  return {
    total,
    completed,
    inMotion,
    turbulent,
    parked,
    progressPercentage,
    averageChaos,
    turbulenceGrade,
    totalEstimatedHours,
  };
}

export function generateMarkdownExport(project: WorkflowProject): string {
  const stats = calculateWorkflowStats(project.steps);
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let md = `# ${project.title}\n`;
  if (project.tagline) md += `*${project.tagline}*\n\n`;
  md += `> Generated by **Chaotic Classifier** — *taming turbulent thoughts*\n`;
  md += `> Export Date: ${dateStr}\n\n`;

  md += `## 📊 Workflow Telemetry\n`;
  md += `- **Progress:** ${stats.progressPercentage}% (${stats.completed}/${stats.total} steps polished)\n`;
  md += `- **Turbulence Index:** ${stats.averageChaos}/5.0 (${stats.turbulenceGrade})\n`;
  md += `- **Estimated Duration:** ${stats.totalEstimatedHours} hours\n`;
  md += `- **Project Category:** ${project.category.toUpperCase()}\n\n`;

  md += `## 🚀 Sequential Step Register\n\n`;

  project.steps.forEach((step, idx) => {
    const statusIcon =
      step.status === 'polished'
        ? '[x] ✨ POLISHED'
        : step.status === 'in_motion'
        ? '[ ] ⚡ IN MOTION'
        : step.status === 'turbulent'
        ? '[ ] 🌪️ TURBULENT'
        : '[ ] 🧊 PARKED';

    const currentBadge = step.isCurrent ? ' `[CURRENT FOCUS]`' : '';

    md += `### ${idx + 1}. ${step.title}${currentBadge}\n`;
    md += `- **Status:** ${statusIcon}\n`;
    md += `- **Category Tag:** \`${step.tag}\` | **Chaos Level:** ${'⭐'.repeat(step.chaosLevel || 1)} (${step.chaosLevel}/5)\n`;
    if (step.estimatedMinutes) {
      md += `- **Est. Time:** ${step.estimatedMinutes} mins\n`;
    }
    md += `\n**Description:**\n${step.description}\n\n`;

    if (step.notes && step.notes.length > 0) {
      md += `**Checklist & Observations:**\n`;
      step.notes.forEach((note) => {
        md += `- ${note}\n`;
      });
      md += `\n`;
    }
    md += `---\n\n`;
  });

  return md;
}

export function getStatusColor(status: WorkflowStep['status']) {
  switch (status) {
    case 'polished':
      return {
        bg: 'bg-emerald-500/10 dark:bg-emerald-950/30',
        text: 'text-emerald-700 dark:text-emerald-400',
        border: 'border-emerald-500/30',
        dot: 'bg-emerald-500',
        label: 'Polished',
        badge: '✨ Polished',
      };
    case 'in_motion':
      return {
        bg: 'bg-indigo-500/10 dark:bg-indigo-950/30',
        text: 'text-indigo-700 dark:text-indigo-400',
        border: 'border-indigo-500/30',
        dot: 'bg-indigo-500 animate-pulse',
        label: 'In Motion',
        badge: '⚡ In Motion',
      };
    case 'turbulent':
      return {
        bg: 'bg-amber-500/10 dark:bg-amber-950/30',
        text: 'text-amber-700 dark:text-amber-400',
        border: 'border-amber-500/30',
        dot: 'bg-amber-500',
        label: 'Turbulent',
        badge: '🌪️ Turbulent',
      };
    case 'parked':
      return {
        bg: 'bg-slate-500/10 dark:bg-slate-800/40',
        text: 'text-slate-600 dark:text-slate-400',
        border: 'border-slate-400/20',
        dot: 'bg-slate-400',
        label: 'Parked',
        badge: '🧊 Parked',
      };
  }
}

export function getChaosLevelDetails(level: number) {
  switch (level) {
    case 5:
      return { label: 'Severe Turbulence', color: 'text-red-500', bar: 'bg-red-500', description: 'Raw, unverified, highly chaotic experiment' };
    case 4:
      return { label: 'High Turbulence', color: 'text-orange-500', bar: 'bg-orange-500', description: 'Active exploration with high unknowns' };
    case 3:
      return { label: 'Moderate Turbulence', color: 'text-amber-500', bar: 'bg-amber-500', description: 'Structured idea with some trial & error' };
    case 2:
      return { label: 'Mild Turbulence', color: 'text-sky-500', bar: 'bg-sky-500', description: 'Clear plan, straightforward execution' };
    case 1:
    default:
      return { label: 'Crystal Clear', color: 'text-emerald-500', bar: 'bg-emerald-500', description: 'Fully defined, deterministic step' };
  }
}
